name: Scan Terraform for Vulnerabilities

on: push

jobs:
  terraform-scan:
    name: Scan Terraform

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Test with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform 
        id: checkov
