name: "PR Security Scanning"

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
jobs:
  # Static analysis security scanning
  security-code-scanning:
    name: Security code scanning
    uses: nmbrs/reusable-workflows/.github/workflows/tfsec-code-scanning.workflow.yaml@main
