name: Scan Terraform for Vulnerabilities on a Schedule

on:
  schedule:
    # every day at 2 am.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '00 2 * * *'   
     

jobs:
  tfsec-scan:
    name: Tfsec Scan 
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          soft-fail: true
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif 
      
      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}          
      